version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - echo "📂 Listing contents of dist directory:"
      - ls -al dist || echo "No dist directory found"
  post_build:
    commands:
      - aws s3 sync dist/ s3://cloudcomputingproject-bucket-3f109847 --delete

artifacts:
  files:
    - "**/*"
  base-directory: dist
